export const CART_CHECKOUT_START = 'CART_CHECKOUT_START';
export const CART_CHECKOUT_SUCCESS = 'CART_CHECKOUT_SUCCESS';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAIL = 'FETCH_CART_FAIL';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const DELETE = 'DELETE';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';

export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const ADD_PRODUCT = 'ADD_PRODUCT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
